# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/latest',
                'doc_host': 'https://fastai.github.io',
                'git_url': 'https://github.com/fastai/latest',
                'lib_path': 'latest'},
  'syms': {'latest.core': {'latest.core.find_releases': ('core.html#find_releases', 'latest/core.py')}}}
