"""API details"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['find_releases']

# %% ../nbs/00_core.ipynb 3
import re
from fasthtml.common import *
from fastcore.all import *

# %% ../nbs/00_core.ipynb 4
def find_releases(path:str):
    "Given a path, find the latest/pre release versions available"
    try: pre,user,repo,*search = path.split('/')
    except ValueError: return '!!!Invalid path'
    if pre not in ('pre', 'latest'): return '!!!first component should be "pre" or "latest"'
    gh = f'https://api.github.com/repos/{user}/{repo}/releases'
    if pre=='latest': gh += '/latest'
    try: rels=urljson(gh)
    except Exception as e: return f'!!!Could not access {gh}; {e}'
    if pre=='pre': rels = rels[0]
    urls = L(rels['assets']).itemgot('browser_download_url')
    if search: urls = [o for o in urls if re.search(search[0], o)]
    return '\n'.join(urls)
